# Configuration for Simple Announcement Plugin

settings:
  enable: false # Enable the auto announcement
  next-announcement-period: 30 #in seconds
  announcement-prefix: "[Simple Announcement]"
  broadcast-prefix: "&c[&lBroadcast]&f"

message:
  broadcast: "%b_prefix% Message From %admin%:&f %message%" # %XXX% is the placeholders. Don't change.
  p2p: "Admin message from %admin%: %message%" # %XXX% is the placeholders. Don't change.
  delivered: "Message sent successfully"
  permission-denied: "Permission Denied"
  player-not-found: "Player Not Found"

announcements:
  - "I am a test announcement"
  - "I am a test announcement 2"
